name: li_battery_modeling
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - torch-geometric
  - pymatgen
  - shap
  - pip
  - pip:
    - joblib

